<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('YourList! ' . $this->translate('Dashboard | Home'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(
                        array(
                            'rel' => 'shortcut icon',
                            'type' => 'image/vnd.microsoft.icon',
                            'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/admin/css/customize-template.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/admin/js/jquery/jquery-1.8.2.min.js')
        ;
        ?>

    </head>
    <body>
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <button class="btn btn-navbar" data-toggle="collapse" data-target="#app-nav-top-bar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="dashboard.html" class="brand"><i class="icon-leaf">YourList! Dashboard</i></a>
                    <div id="app-nav-top-bar" class="nav-collapse">
                        <ul class="nav pull-right">
                            <li>
                                <a href="login.html">Logout</a>
                            </li>

                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div id="body-container">
            <div id="body-content">

                <div class="body-nav body-nav-horizontal body-nav-fixed">
                    <div class="container">
                        <ul>
                            <li>
                                <a href="#">
                                    <i class="icon-dashboard icon-large"></i> Dashboard
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="icon-calendar icon-large"></i> Schedule
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="icon-map-marker icon-large"></i> Map It
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="icon-tasks icon-large"></i> Widgets
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="icon-cogs icon-large"></i> Settings
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="icon-list-alt icon-large"></i> Forms
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="icon-bar-chart icon-large"></i> Charts
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>

                <?php echo $this->content; ?>

            </div>
        </div>

        <div id="spinner" class="spinner" style="display:none;">
            Loading&hellip;
        </div>

        <footer class="application-footer">
            <div class="container">
                <p>Application Footer</p>
                <div class="disclaimer">
                    <p>This is an example disclaimer. All right reserved.</p>
                    <p>Copyright © keaplogik 2011-2012</p>
                </div>
            </div>
        </footer>

        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/admin/js/bootstrap/bootstrap-transition.js')
                ->prependFile($this->basePath() . '/admin/js/bootstrap/bootstrap-alert.js')
                ->prependFile($this->basePath() . '/admin/js/bootstrap/bootstrap-modal.js')
                ->prependFile($this->basePath() . '/admin/js/bootstrap/bootstrap-dropdown.js')
                ->prependFile($this->basePath() . '/admin/js/bootstrap/bootstrap-scrollspy.js')
                ->prependFile($this->basePath() . '/admin/js/bootstrap/bootstrap-tab.js')
                ->prependFile($this->basePath() . '/admin/js/bootstrap/bootstrap-tooltip.js')
                ->prependFile($this->basePath() . '/admin/js/bootstrap/bootstrap-popover.js')
                ->prependFile($this->basePath() . '/admin/js/bootstrap/bootstrap-button.js')
                ->prependFile($this->basePath() . '/admin/js/bootstrap/bootstrap-collapse.js')
                ->prependFile($this->basePath() . '/admin/js/bootstrap/bootstrap-carousel.js')
                ->prependFile($this->basePath() . '/admin/js/bootstrap/bootstrap-typeahead.js')
                ->prependFile($this->basePath() . '/admin/js/bootstrap/bootstrap-affix.js')
                ->prependFile($this->basePath() . '/admin/js/bootstrap/bootstrap-datepicker.js')
                ->prependFile($this->basePath() . '/admin/js/jquery/jquery-tablesorter.js')
                ->prependFile($this->basePath() . '/admin/js/jquery/jquery-chosen.js')
                ->prependFile($this->basePath() . '/admin/js/jquery/virtual-tour.js')
        ;
        ?>
        <script type="text/javascript">
            $(function() {
                $('#sample-table').tablesorter();
                $('#datepicker').datepicker();
                $(".chosen").chosen();
            });
        </script>

    </body>
</html>